#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="kvmod"
device="kv_mod"
mode="664"

# Group: since distributions do it differently, I used the group "adm"
group="lfs"

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$device\" {print \$1}" /proc/devices)
echo $major

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -vf /dev/${device}0
mknod /dev/${device}0 c $major 0
ln -svf ${device}0 /dev/${device}
chgrp -v $group /dev/${device}0 
chmod -v $mode  /dev/${device}0

